### ISSUE TITLE
Menu text is not aligned

### ISSUE THREAD

**Issue by Aholicknight** [ruckage/es-theme-snes-mini#29] opened 2022-03-30 00:29 UTC
I am using the latest version of the SNES Mini theme and for some reason the text in the games section is not centered. 

https://user-images.githubusercontent.com/7843719/160727421-9443395b-1963-4306-b9c2-68f87579f16b.mp4

This is the video of the problem, if anyone can help me or provide support, that would be great. Thank you!

**Comment by thias** [comment] 2022-04-25 18:34
Duplicate of #22

**Closed as completed** 2022-06-16 05:20 UTC
